from typing import Any

COMPETENCY_CATALOG: list[dict[str, Any]] = [
    {
        "slug": "python-fundamentals",
        "name": "Python Fundamentals",
        "description": "Write and debug small Python programs using core language constructs.",
        "category": "programming",
        "prerequisite_slugs": [],
    },
    {
        "slug": "data-analysis-python",
        "name": "Data Analysis with Python",
        "description": "Load, clean, transform, and inspect tabular data with Python.",
        "category": "data",
        "prerequisite_slugs": ["python-fundamentals"],
    },
    {
        "slug": "probability",
        "name": "Probability",
        "description": "Apply probability rules, distributions, expectation, and uncertainty.",
        "category": "mathematics",
        "prerequisite_slugs": ["algebra-functions"],
    },
    {
        "slug": "statistics",
        "name": "Statistics",
        "description": "Use descriptive and inferential statistics to evaluate data and models.",
        "category": "mathematics",
        "prerequisite_slugs": ["probability"],
    },
    {
        "slug": "linear-algebra",
        "name": "Linear Algebra",
        "description": "Work with vectors, matrices, transformations, and basic decompositions.",
        "category": "mathematics",
        "prerequisite_slugs": ["algebra-functions"],
    },
    {
        "slug": "machine-learning-fundamentals",
        "name": "Machine Learning Fundamentals",
        "description": "Train, validate, and interpret foundational supervised learning models.",
        "category": "machine-learning",
        "prerequisite_slugs": [
            "data-analysis-python",
            "statistics",
            "linear-algebra",
        ],
    },
    {
        "slug": "ml-project-practice",
        "name": "Machine Learning Project Practice",
        "description": "Deliver reproducible end-to-end machine learning projects.",
        "category": "machine-learning",
        "prerequisite_slugs": ["machine-learning-fundamentals"],
    },
    {
        "slug": "programming-problem-solving",
        "name": "Programming Problem Solving",
        "description": "Translate requirements into correct, testable programs.",
        "category": "programming",
        "prerequisite_slugs": [],
    },
    {
        "slug": "complexity-analysis",
        "name": "Complexity Analysis",
        "description": "Reason about time and space complexity using asymptotic notation.",
        "category": "computer-science",
        "prerequisite_slugs": ["programming-problem-solving"],
    },
    {
        "slug": "arrays-hash-maps",
        "name": "Arrays and Hash Maps",
        "description": "Solve interview problems using indexed and key-value data structures.",
        "category": "computer-science",
        "prerequisite_slugs": ["programming-problem-solving", "complexity-analysis"],
    },
    {
        "slug": "recursion-trees",
        "name": "Recursion and Trees",
        "description": "Model recursive solutions and traverse common tree structures.",
        "category": "computer-science",
        "prerequisite_slugs": ["arrays-hash-maps"],
    },
    {
        "slug": "graphs-dynamic-programming",
        "name": "Graphs and Dynamic Programming",
        "description": "Apply graph traversal and dynamic programming patterns.",
        "category": "computer-science",
        "prerequisite_slugs": ["recursion-trees"],
    },
    {
        "slug": "technical-interview-practice",
        "name": "Technical Interview Practice",
        "description": "Solve timed interview problems and communicate reasoning clearly.",
        "category": "career",
        "prerequisite_slugs": ["arrays-hash-maps", "recursion-trees"],
    },
    {
        "slug": "algebra-functions",
        "name": "Algebra and Functions",
        "description": "Manipulate expressions and reason about functions and their graphs.",
        "category": "mathematics",
        "prerequisite_slugs": [],
    },
    {
        "slug": "limits-continuity",
        "name": "Limits and Continuity",
        "description": "Evaluate limits and determine continuity analytically and graphically.",
        "category": "mathematics",
        "prerequisite_slugs": ["algebra-functions"],
    },
    {
        "slug": "derivatives",
        "name": "Derivatives",
        "description": "Differentiate functions and apply rates of change and optimization.",
        "category": "mathematics",
        "prerequisite_slugs": ["limits-continuity"],
    },
    {
        "slug": "integrals",
        "name": "Integrals",
        "description": "Compute and interpret definite and indefinite integrals.",
        "category": "mathematics",
        "prerequisite_slugs": ["derivatives"],
    },
    {
        "slug": "calculus-exam-practice",
        "name": "Calculus Exam Practice",
        "description": "Solve mixed calculus problems accurately under exam time limits.",
        "category": "mathematics",
        "prerequisite_slugs": ["derivatives", "integrals"],
    },
]


GOAL_TEMPLATE_CATALOG: list[dict[str, Any]] = [
    {
        "slug": "machine-learning-internship",
        "name": "Machine Learning Internship Readiness",
        "description": (
            "Prepare foundational knowledge and portfolio evidence for an ML internship."
        ),
        "category": "career",
        "matching_terms": [
            "machine learning",
            "machine learning internship",
            "learn ml",
            "ml internship",
            "data science internship",
            "ml engineer",
        ],
        "default_duration_weeks": 16,
        "default_target_level": 3,
        "measurable_outcome": (
            "Become ready to apply for an entry-level machine learning internship "
            "with two reviewed portfolio projects"
        ),
        "success_criteria": [
            "Complete two reproducible machine learning portfolio projects",
            "Explain model selection and evaluation decisions for each project",
            "Reach independent application level in machine learning fundamentals",
            "Complete a timed mock technical interview",
        ],
        "requirements": [
            {
                "competency_slug": "python-fundamentals",
                "target_level": 3,
                "estimated_hours": 24,
                "required": True,
                "prerequisite_slugs": [],
            },
            {
                "competency_slug": "algebra-functions",
                "target_level": 2,
                "estimated_hours": 14,
                "required": True,
                "prerequisite_slugs": [],
            },
            {
                "competency_slug": "data-analysis-python",
                "target_level": 3,
                "estimated_hours": 28,
                "required": True,
                "prerequisite_slugs": ["python-fundamentals"],
            },
            {
                "competency_slug": "probability",
                "target_level": 2,
                "estimated_hours": 20,
                "required": True,
                "prerequisite_slugs": ["algebra-functions"],
            },
            {
                "competency_slug": "statistics",
                "target_level": 3,
                "estimated_hours": 30,
                "required": True,
                "prerequisite_slugs": ["probability"],
            },
            {
                "competency_slug": "linear-algebra",
                "target_level": 2,
                "estimated_hours": 22,
                "required": True,
                "prerequisite_slugs": ["algebra-functions"],
            },
            {
                "competency_slug": "machine-learning-fundamentals",
                "target_level": 3,
                "estimated_hours": 48,
                "required": True,
                "prerequisite_slugs": [
                    "data-analysis-python",
                    "statistics",
                    "linear-algebra",
                ],
            },
            {
                "competency_slug": "ml-project-practice",
                "target_level": 3,
                "estimated_hours": 44,
                "required": True,
                "prerequisite_slugs": ["machine-learning-fundamentals"],
            },
        ],
    },
    {
        "slug": "data-structures-interview",
        "name": "Data Structures Interview Preparation",
        "description": "Build interview-ready data structures and algorithm problem-solving skill.",
        "category": "career",
        "matching_terms": [
            "data structures",
            "dsa interview",
            "coding interview",
            "algorithms interview",
        ],
        "default_duration_weeks": 10,
        "default_target_level": 3,
        "measurable_outcome": (
            "Solve common data structures interview problems under timed conditions "
            "and explain the complexity of each solution"
        ),
        "success_criteria": [
            "Solve at least 45 representative interview problems",
            "Explain time and space complexity without prompting",
            "Complete three timed mock interviews",
            "Independently solve medium problems across arrays, trees, and graphs",
        ],
        "requirements": [
            {
                "competency_slug": "programming-problem-solving",
                "target_level": 3,
                "estimated_hours": 20,
                "required": True,
                "prerequisite_slugs": [],
            },
            {
                "competency_slug": "complexity-analysis",
                "target_level": 3,
                "estimated_hours": 14,
                "required": True,
                "prerequisite_slugs": ["programming-problem-solving"],
            },
            {
                "competency_slug": "arrays-hash-maps",
                "target_level": 3,
                "estimated_hours": 24,
                "required": True,
                "prerequisite_slugs": [
                    "programming-problem-solving",
                    "complexity-analysis",
                ],
            },
            {
                "competency_slug": "recursion-trees",
                "target_level": 3,
                "estimated_hours": 30,
                "required": True,
                "prerequisite_slugs": ["arrays-hash-maps"],
            },
            {
                "competency_slug": "graphs-dynamic-programming",
                "target_level": 2,
                "estimated_hours": 34,
                "required": False,
                "prerequisite_slugs": ["recursion-trees"],
            },
            {
                "competency_slug": "technical-interview-practice",
                "target_level": 3,
                "estimated_hours": 28,
                "required": True,
                "prerequisite_slugs": ["arrays-hash-maps", "recursion-trees"],
            },
        ],
    },
    {
        "slug": "calculus-exam",
        "name": "Calculus Exam Preparation",
        "description": "Prepare for a college calculus exam with prerequisite-aware practice.",
        "category": "academic",
        "matching_terms": [
            "calculus exam",
            "pass calculus",
            "calculus test",
            "derivatives exam",
            "integrals exam",
        ],
        "default_duration_weeks": 6,
        "default_target_level": 3,
        "measurable_outcome": (
            "Score at least 75 percent on a timed calculus practice exam before the target date"
        ),
        "success_criteria": [
            "Score at least 75 percent on two timed mixed-topic practice exams",
            "Solve derivative and integral problems without reference notes",
            "Identify prerequisite algebra errors during review",
            "Complete spaced review across all required topics",
        ],
        "requirements": [
            {
                "competency_slug": "algebra-functions",
                "target_level": 3,
                "estimated_hours": 14,
                "required": True,
                "prerequisite_slugs": [],
            },
            {
                "competency_slug": "limits-continuity",
                "target_level": 3,
                "estimated_hours": 18,
                "required": True,
                "prerequisite_slugs": ["algebra-functions"],
            },
            {
                "competency_slug": "derivatives",
                "target_level": 3,
                "estimated_hours": 24,
                "required": True,
                "prerequisite_slugs": ["limits-continuity"],
            },
            {
                "competency_slug": "integrals",
                "target_level": 3,
                "estimated_hours": 26,
                "required": True,
                "prerequisite_slugs": ["derivatives"],
            },
            {
                "competency_slug": "calculus-exam-practice",
                "target_level": 3,
                "estimated_hours": 20,
                "required": True,
                "prerequisite_slugs": ["derivatives", "integrals"],
            },
        ],
    },
]
