"""phase 1 platform kernel

Revision ID: 3ec66d7f2e87
Revises: 
Create Date: 2026-07-30 10:28:17.422506
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '3ec66d7f2e87'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('role', sa.Enum('student', 'admin', name='role', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('active', 'suspended', 'deleted', name='userstatus', native_enum=False), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=True),
    sa.Column('oidc_issuer', sa.String(length=512), nullable=True),
    sa.Column('oidc_subject', sa.String(length=255), nullable=True),
    sa.Column('auth_version', sa.Integer(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('student', 'admin')", name=op.f('ck_users_role_allowed')),
    sa.CheckConstraint("status IN ('active', 'suspended', 'deleted')", name=op.f('ck_users_status_allowed')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('oidc_issuer', 'oidc_subject', name='uq_users_oidc_identity')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_role', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('resource_type', sa.String(length=80), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('before_data', sa.JSON(), nullable=True),
    sa.Column('after_data', sa.JSON(), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=False),
    sa.Column('previous_hash', sa.String(length=64), nullable=True),
    sa.Column('event_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_audit_logs_student_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs')),
    sa.UniqueConstraint('event_hash', name=op.f('uq_audit_logs_event_hash'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_occurred_at'), 'audit_logs', ['occurred_at'], unique=False)
    op.create_index('ix_audit_logs_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_student_id'), 'audit_logs', ['student_id'], unique=False)
    op.create_index('ix_audit_logs_student_time', 'audit_logs', ['student_id', 'occurred_at'], unique=False)
    op.create_table('auth_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_session_id', sa.Uuid(), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['replaced_by_session_id'], ['auth_sessions.id'], name=op.f('fk_auth_sessions_replaced_by_session_id_auth_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_sessions')),
    sa.UniqueConstraint('refresh_token_hash', name=op.f('uq_auth_sessions_refresh_token_hash'))
    )
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.create_table('goals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('raw_statement', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'paused', 'completed', 'closed', name='goalstatus', native_enum=False), nullable=False),
    sa.Column('success_criteria', sa.JSON(), nullable=False),
    sa.Column('assumptions', sa.JSON(), nullable=False),
    sa.Column('paused_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'active', 'paused', 'completed', 'closed')", name=op.f('ck_goals_status_allowed')),
    sa.CheckConstraint('priority >= 1 AND priority <= 5', name=op.f('ck_goals_priority_valid')),
    sa.CheckConstraint('version > 0', name=op.f('ck_goals_version_positive')),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_goals_student_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goals'))
    )
    op.create_index('ix_goals_student_status', 'goals', ['student_id', 'status'], unique=False)
    op.create_table('student_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('education_level', sa.String(length=120), nullable=True),
    sa.Column('institution', sa.String(length=200), nullable=True),
    sa.Column('weekly_learning_minutes', sa.Integer(), nullable=False),
    sa.Column('learning_preferences', sa.JSON(), nullable=False),
    sa.Column('availability', sa.JSON(), nullable=False),
    sa.Column('device_access', sa.JSON(), nullable=False),
    sa.Column('accessibility_needs', sa.JSON(), nullable=False),
    sa.Column('consent_scopes', sa.JSON(), nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('version > 0', name=op.f('ck_student_profiles_version_positive')),
    sa.CheckConstraint('weekly_learning_minutes >= 0 AND weekly_learning_minutes <= 10080', name=op.f('ck_student_profiles_weekly_minutes_valid')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_student_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_student_profiles_user_id'))
    )
    op.create_table('goal_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('goal_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('changed_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('change_type', sa.String(length=40), nullable=False),
    sa.Column('change_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], name=op.f('fk_goal_versions_changed_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], name=op.f('fk_goal_versions_goal_id_goals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goal_versions')),
    sa.UniqueConstraint('goal_id', 'version', name='uq_goal_versions_goal_version')
    )
    op.create_table('student_profile_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('changed_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('change_reason', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], name=op.f('fk_student_profile_versions_changed_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['profile_id'], ['student_profiles.id'], name=op.f('fk_student_profile_versions_profile_id_student_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_profile_versions')),
    sa.UniqueConstraint('profile_id', 'version', name='uq_profile_versions_profile_version')
    )
    op.create_table('workflow_states',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workflow_type', sa.String(length=80), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('goal_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'input_required', 'approval_required', 'completed', 'failed', 'cancelled', name='workflowstatus', native_enum=False), nullable=False),
    sa.Column('current_step', sa.String(length=80), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('state_data', sa.JSON(), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'running', 'input_required', 'approval_required', 'completed', 'failed', 'cancelled')", name=op.f('ck_workflow_states_status_allowed')),
    sa.CheckConstraint('version > 0', name=op.f('ck_workflow_states_version_positive')),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], name=op.f('fk_workflow_states_goal_id_goals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_workflow_states_student_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_states'))
    )
    op.create_index(op.f('ix_workflow_states_correlation_id'), 'workflow_states', ['correlation_id'], unique=False)
    op.create_index('ix_workflow_states_student_status', 'workflow_states', ['student_id', 'status'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('agent_name', sa.String(length=120), nullable=False),
    sa.Column('agent_version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('running', 'completed', 'input_required', 'student_approval_required', 'admin_review_required', 'blocked', 'failed', name='agentrunstatus', native_enum=False), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('prompt_version', sa.String(length=40), nullable=False),
    sa.Column('model_route', sa.String(length=80), nullable=False),
    sa.Column('policy_version', sa.String(length=40), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('output_hash', sa.String(length=64), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.CheckConstraint("status IN ('running', 'completed', 'input_required', 'student_approval_required', 'admin_review_required', 'blocked', 'failed')", name=op.f('ck_agent_runs_status_allowed')),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_agent_runs_actor_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow_states.id'], name=op.f('fk_agent_runs_workflow_id_workflow_states'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_runs')),
    sa.UniqueConstraint('idempotency_key', name='uq_agent_runs_idempotency_key')
    )
    op.create_index(op.f('ix_agent_runs_workflow_id'), 'agent_runs', ['workflow_id'], unique=False)
    if op.get_bind().dialect.name == "postgresql":
        op.execute(
            """
            CREATE FUNCTION prevent_audit_log_mutation()
            RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'audit_logs are immutable';
            END;
            $$ LANGUAGE plpgsql;
            """
        )
        op.execute(
            """
            CREATE TRIGGER audit_logs_immutable
            BEFORE UPDATE OR DELETE ON audit_logs
            FOR EACH ROW EXECUTE FUNCTION prevent_audit_log_mutation();
            """
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP TRIGGER IF EXISTS audit_logs_immutable ON audit_logs")
        op.execute("DROP FUNCTION IF EXISTS prevent_audit_log_mutation()")
    op.drop_index(op.f('ix_agent_runs_workflow_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index('ix_workflow_states_student_status', table_name='workflow_states')
    op.drop_index(op.f('ix_workflow_states_correlation_id'), table_name='workflow_states')
    op.drop_table('workflow_states')
    op.drop_table('student_profile_versions')
    op.drop_table('goal_versions')
    op.drop_table('student_profiles')
    op.drop_index('ix_goals_student_status', table_name='goals')
    op.drop_table('goals')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index('ix_audit_logs_student_time', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_student_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_resource', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_occurred_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
