"""phase 4 adaptive learning integration

Revision ID: be21515c6e1c
Revises: c4d9e3f1a672
Create Date: 2026-07-30 12:06:38.452061
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "be21515c6e1c"
down_revision: str | None = "c4d9e3f1a672"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_resources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('competency_ref', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('provider', sa.String(length=160), nullable=False),
    sa.Column('resource_type', sa.String(length=40), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('cost_amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('license_name', sa.String(length=120), nullable=True),
    sa.Column('content_excerpt', sa.Text(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'approved', 'rejected', 'stale')", name=op.f('ck_learning_resources_status_allowed')),
    sa.CheckConstraint('cost_amount >= 0', name=op.f('ck_learning_resources_cost_nonnegative')),
    sa.CheckConstraint('difficulty >= 1 AND difficulty <= 5', name=op.f('ck_learning_resources_difficulty_valid')),
    sa.CheckConstraint('quality_score >= 0 AND quality_score <= 1', name=op.f('ck_learning_resources_quality_valid')),
    sa.CheckConstraint('version > 0', name=op.f('ck_learning_resources_version_positive')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_learning_resources_created_by_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_resources')),
    sa.UniqueConstraint('url', name=op.f('uq_learning_resources_url'))
    )
    op.create_index('ix_learning_resources_competency_status', 'learning_resources', ['competency_ref', 'status'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('notification_type', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('related_type', sa.String(length=80), nullable=True),
    sa.Column('related_id', sa.String(length=128), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_notifications_student_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_notifications_student_unread', 'notifications', ['student_id', 'read_at'], unique=False)
    op.create_table('phase4_storage_receipts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('media_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('scanner_status', sa.String(length=20), nullable=False),
    sa.Column('verified_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("scanner_status IN ('clean', 'quarantined')", name=op.f('ck_phase4_storage_receipts_scanner_status_allowed')),
    sa.CheckConstraint('size_bytes > 0', name=op.f('ck_phase4_storage_receipts_size_positive')),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['users.id'], name=op.f('fk_phase4_storage_receipts_verified_by_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_phase4_storage_receipts')),
    sa.UniqueConstraint('storage_key', name='uq_phase4_storage_receipts_key')
    )
    op.create_table('assessment_definitions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('goal_id', sa.Uuid(), nullable=False),
    sa.Column('competency_ref', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('assessment_type', sa.String(length=40), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.Column('rubric', sa.JSON(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('passing_percentage', sa.Float(), nullable=False),
    sa.Column('time_limit_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'published', 'retired')", name=op.f('ck_assessment_definitions_status_allowed')),
    sa.CheckConstraint('max_score > 0', name=op.f('ck_assessment_definitions_max_score_positive')),
    sa.CheckConstraint('passing_percentage >= 0 AND passing_percentage <= 100', name=op.f('ck_assessment_definitions_passing_valid')),
    sa.CheckConstraint('version > 0', name=op.f('ck_assessment_definitions_version_positive')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_assessment_definitions_created_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], name=op.f('fk_assessment_definitions_goal_id_goals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_definitions'))
    )
    op.create_index('ix_assessment_definitions_goal_status', 'assessment_definitions', ['goal_id', 'status'], unique=False)
    op.create_table('coaching_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('goal_id', sa.Uuid(), nullable=False),
    sa.Column('check_in', sa.Text(), nullable=False),
    sa.Column('motivation_level', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('reflection_prompt', sa.Text(), nullable=False),
    sa.Column('habit_experiment', sa.Text(), nullable=False),
    sa.Column('notification_adjustment', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], name=op.f('fk_coaching_records_goal_id_goals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_coaching_records_student_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coaching_records'))
    )
    op.create_index('ix_coaching_records_student_goal', 'coaching_records', ['student_id', 'goal_id'], unique=False)
    op.create_table('focus_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('goal_id', sa.Uuid(), nullable=False),
    sa.Column('task_ref', sa.String(length=120), nullable=True),
    sa.Column('milestone_ref', sa.String(length=120), nullable=True),
    sa.Column('objective', sa.String(length=500), nullable=False),
    sa.Column('planned_minutes', sa.Integer(), nullable=False),
    sa.Column('actual_minutes', sa.Integer(), nullable=True),
    sa.Column('distraction_count', sa.Integer(), nullable=False),
    sa.Column('blocker_notes', sa.JSON(), nullable=False),
    sa.Column('reflection', sa.Text(), nullable=True),
    sa.Column('accomplished', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('active', 'completed', 'abandoned')", name=op.f('ck_focus_sessions_status_allowed')),
    sa.CheckConstraint('planned_minutes >= 5', name=op.f('ck_focus_sessions_planned_minutes_valid')),
    sa.CheckConstraint('version > 0', name=op.f('ck_focus_sessions_version_positive')),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], name=op.f('fk_focus_sessions_goal_id_goals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_focus_sessions_student_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_focus_sessions')),
    sa.UniqueConstraint('idempotency_key', name='uq_focus_sessions_idempotency')
    )
    op.create_index('ix_focus_sessions_student_goal', 'focus_sessions', ['student_id', 'goal_id'], unique=False)
    op.create_table('mastery_estimates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('goal_id', sa.Uuid(), nullable=False),
    sa.Column('competency_ref', sa.String(length=120), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('confidence_lower', sa.Float(), nullable=False),
    sa.Column('confidence_upper', sa.Float(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('weak_subskills', sa.JSON(), nullable=False),
    sa.Column('next_assessment_recommendation', sa.Text(), nullable=False),
    sa.Column('calculation', sa.JSON(), nullable=False),
    sa.Column('estimated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('confidence_lower >= 0 AND confidence_lower <= 1', name=op.f('ck_mastery_estimates_lower_valid')),
    sa.CheckConstraint('confidence_upper >= 0 AND confidence_upper <= 1', name=op.f('ck_mastery_estimates_upper_valid')),
    sa.CheckConstraint('score >= 0 AND score <= 1', name=op.f('ck_mastery_estimates_score_valid')),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], name=op.f('fk_mastery_estimates_goal_id_goals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_mastery_estimates_student_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mastery_estimates')),
    sa.UniqueConstraint('goal_id', 'competency_ref', 'version', name='uq_mastery_estimates_goal_competency_version')
    )
    op.create_index('ix_mastery_estimates_goal_competency', 'mastery_estimates', ['goal_id', 'competency_ref'], unique=False)
    op.create_table('phase4_agent_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=True),
    sa.Column('goal_id', sa.Uuid(), nullable=True),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('agent_name', sa.String(length=120), nullable=False),
    sa.Column('agent_version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('prompt_version', sa.String(length=40), nullable=False),
    sa.Column('model_route', sa.String(length=80), nullable=False),
    sa.Column('policy_version', sa.String(length=40), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('output_hash', sa.String(length=64), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.CheckConstraint("status IN ('running', 'completed', 'input_required', 'admin_review_required', 'student_approval_required', 'blocked', 'failed')", name=op.f('ck_phase4_agent_runs_status_allowed')),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_phase4_agent_runs_actor_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], name=op.f('fk_phase4_agent_runs_goal_id_goals'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_phase4_agent_runs_student_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_phase4_agent_runs')),
    sa.UniqueConstraint('idempotency_key', name='uq_phase4_agent_runs_idempotency')
    )
    op.create_index('ix_phase4_agent_runs_student_goal', 'phase4_agent_runs', ['student_id', 'goal_id'], unique=False)
    op.create_table('phase4_execution_contexts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('goal_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('plan_ref', sa.String(length=120), nullable=True),
    sa.Column('plan_version', sa.Integer(), nullable=True),
    sa.Column('planned_task_count', sa.Integer(), nullable=False),
    sa.Column('completed_task_count', sa.Integer(), nullable=False),
    sa.Column('planned_milestone_count', sa.Integer(), nullable=False),
    sa.Column('completed_milestone_count', sa.Integer(), nullable=False),
    sa.Column('planned_weekly_minutes', sa.Integer(), nullable=False),
    sa.Column('weekly_capacity_minutes', sa.Integer(), nullable=False),
    sa.Column('schedule_adherence', sa.Float(), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('completed_milestone_count <= planned_milestone_count', name=op.f('ck_phase4_execution_contexts_milestone_totals_valid')),
    sa.CheckConstraint('completed_task_count <= planned_task_count', name=op.f('ck_phase4_execution_contexts_task_totals_valid')),
    sa.CheckConstraint('schedule_adherence >= 0 AND schedule_adherence <= 1', name=op.f('ck_phase4_execution_contexts_adherence_valid')),
    sa.CheckConstraint('version > 0', name=op.f('ck_phase4_execution_contexts_version_positive')),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], name=op.f('fk_phase4_execution_contexts_goal_id_goals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_phase4_execution_contexts_student_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_phase4_execution_contexts')),
    sa.UniqueConstraint('goal_id', name='uq_phase4_execution_contexts_goal')
    )
    op.create_index(op.f('ix_phase4_execution_contexts_student_id'), 'phase4_execution_contexts', ['student_id'], unique=False)
    op.create_table('progress_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('goal_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('source_type', sa.String(length=80), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('activity_points', sa.Float(), nullable=False),
    sa.Column('mastery_signal', sa.Float(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], name=op.f('fk_progress_events_goal_id_goals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_progress_events_student_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_progress_events')),
    sa.UniqueConstraint('idempotency_key', name='uq_progress_events_idempotency')
    )
    op.create_index('ix_progress_events_student_goal_time', 'progress_events', ['student_id', 'goal_id', 'occurred_at'], unique=False)
    op.create_table('progress_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('goal_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('activity_progress', sa.Float(), nullable=False),
    sa.Column('milestone_progress', sa.Float(), nullable=False),
    sa.Column('mastery_progress', sa.Float(), nullable=False),
    sa.Column('goal_confidence', sa.Float(), nullable=False),
    sa.Column('schedule_variance', sa.Float(), nullable=False),
    sa.Column('verified_evidence_count', sa.Integer(), nullable=False),
    sa.Column('assessment_count', sa.Integer(), nullable=False),
    sa.Column('focus_minutes', sa.Integer(), nullable=False),
    sa.Column('calculation', sa.JSON(), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('version > 0', name=op.f('ck_progress_snapshots_version_positive')),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], name=op.f('fk_progress_snapshots_goal_id_goals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_progress_snapshots_student_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_progress_snapshots')),
    sa.UniqueConstraint('goal_id', 'version', name='uq_progress_snapshots_goal_version')
    )
    op.create_index('ix_progress_snapshots_goal_time', 'progress_snapshots', ['goal_id', 'as_of'], unique=False)
    op.create_table('resource_recommendations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('goal_id', sa.Uuid(), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('competency_ref', sa.String(length=120), nullable=False),
    sa.Column('request_key', sa.String(length=128), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('selection_reason', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('relevance_score >= 0 AND relevance_score <= 1', name=op.f('ck_resource_recommendations_relevance_valid')),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], name=op.f('fk_resource_recommendations_goal_id_goals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['learning_resources.id'], name=op.f('fk_resource_recommendations_resource_id_learning_resources'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_resource_recommendations_student_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resource_recommendations')),
    sa.UniqueConstraint('student_id', 'goal_id', 'resource_id', 'request_key', name='uq_resource_recommendations_request_resource')
    )
    op.create_table('risks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('goal_id', sa.Uuid(), nullable=False),
    sa.Column('risk_type', sa.String(length=80), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('evidence_refs', sa.JSON(), nullable=False),
    sa.Column('likely_causes', sa.JSON(), nullable=False),
    sa.Column('intervention', sa.Text(), nullable=False),
    sa.Column('requires_admin_review', sa.Boolean(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("severity IN ('low', 'medium', 'high', 'critical')", name=op.f('ck_risks_severity_allowed')),
    sa.CheckConstraint("status IN ('open', 'mitigated', 'dismissed')", name=op.f('ck_risks_status_allowed')),
    sa.CheckConstraint('score >= 0 AND score <= 1', name=op.f('ck_risks_score_valid')),
    sa.CheckConstraint('version > 0', name=op.f('ck_risks_version_positive')),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], name=op.f('fk_risks_goal_id_goals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_risks_student_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risks'))
    )
    op.create_index('ix_risks_student_goal_status', 'risks', ['student_id', 'goal_id', 'status'], unique=False)
    op.create_table('tutor_threads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('goal_id', sa.Uuid(), nullable=False),
    sa.Column('competency_ref', sa.String(length=120), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], name=op.f('fk_tutor_threads_goal_id_goals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_tutor_threads_student_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tutor_threads'))
    )
    op.create_index('ix_tutor_threads_student_goal', 'tutor_threads', ['student_id', 'goal_id'], unique=False)
    op.create_table('assessment_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('feedback', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('scored', 'review_required')", name=op.f('ck_assessment_attempts_status_allowed')),
    sa.CheckConstraint('percentage >= 0 AND percentage <= 100', name=op.f('ck_assessment_attempts_percentage_valid')),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment_definitions.id'], name=op.f('fk_assessment_attempts_assessment_id_assessment_definitions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_assessment_attempts_student_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_attempts')),
    sa.UniqueConstraint('assessment_id', 'student_id', 'attempt_number', name='uq_assessment_attempts_number'),
    sa.UniqueConstraint('idempotency_key', name='uq_assessment_attempts_idempotency')
    )
    op.create_index('ix_assessment_attempts_student', 'assessment_attempts', ['student_id', 'submitted_at'], unique=False)
    op.create_table('replan_proposals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('goal_id', sa.Uuid(), nullable=False),
    sa.Column('risk_id', sa.Uuid(), nullable=False),
    sa.Column('base_plan_ref', sa.String(length=120), nullable=False),
    sa.Column('base_plan_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('proposed_patch', sa.JSON(), nullable=False),
    sa.Column('impact_analysis', sa.JSON(), nullable=False),
    sa.Column('alternatives', sa.JSON(), nullable=False),
    sa.Column('preserves_completed_work', sa.Boolean(), nullable=False),
    sa.Column('student_approval_required', sa.Boolean(), nullable=False),
    sa.Column('admin_review_required', sa.Boolean(), nullable=False),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applied_plan_ref', sa.String(length=120), nullable=True),
    sa.Column('applied_plan_version', sa.Integer(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('proposed', 'approved_pending_phase3', 'rejected', 'applied')", name=op.f('ck_replan_proposals_status_allowed')),
    sa.CheckConstraint('version > 0', name=op.f('ck_replan_proposals_version_positive')),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], name=op.f('fk_replan_proposals_goal_id_goals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], name=op.f('fk_replan_proposals_risk_id_risks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_replan_proposals_student_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_replan_proposals'))
    )
    op.create_index('ix_replan_proposals_student_goal', 'replan_proposals', ['student_id', 'goal_id'], unique=False)
    op.create_table('tutor_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('thread_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('citations', sa.JSON(), nullable=False),
    sa.Column('integrity_boundary_applied', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['tutor_threads.id'], name=op.f('fk_tutor_messages_thread_id_tutor_threads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tutor_messages'))
    )
    op.create_index('ix_tutor_messages_thread_time', 'tutor_messages', ['thread_id', 'created_at'], unique=False)
    op.create_table('evidence_submissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('goal_id', sa.Uuid(), nullable=False),
    sa.Column('competency_ref', sa.String(length=120), nullable=False),
    sa.Column('task_ref', sa.String(length=120), nullable=True),
    sa.Column('milestone_ref', sa.String(length=120), nullable=True),
    sa.Column('assessment_attempt_id', sa.Uuid(), nullable=True),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('media_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('acceptance_criteria', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'verified', 'rejected', 'resubmission_required', 'admin_review_required')", name=op.f('ck_evidence_submissions_status_allowed')),
    sa.CheckConstraint('size_bytes > 0', name=op.f('ck_evidence_submissions_size_positive')),
    sa.ForeignKeyConstraint(['assessment_attempt_id'], ['assessment_attempts.id'], name=op.f('fk_evidence_submissions_assessment_attempt_id_assessment_attempts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], name=op.f('fk_evidence_submissions_goal_id_goals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_evidence_submissions_student_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_submissions')),
    sa.UniqueConstraint('idempotency_key', name='uq_evidence_submissions_idempotency'),
    sa.UniqueConstraint('student_id', 'goal_id', 'sha256', name='uq_evidence_submissions_content')
    )
    op.create_index('ix_evidence_submissions_student_goal', 'evidence_submissions', ['student_id', 'goal_id'], unique=False)
    op.create_table('evidence_reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('evidence_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer_type', sa.String(length=20), nullable=False),
    sa.Column('reviewer_id', sa.Uuid(), nullable=True),
    sa.Column('decision', sa.String(length=40), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('criteria_results', sa.JSON(), nullable=False),
    sa.Column('integrity_flags', sa.JSON(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence_submissions.id'], name=op.f('fk_evidence_reviews_evidence_id_evidence_submissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_evidence_reviews_reviewer_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_reviews'))
    )
    op.create_index(op.f('ix_evidence_reviews_evidence_id'), 'evidence_reviews', ['evidence_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_reviews_evidence_id'), table_name='evidence_reviews')
    op.drop_table('evidence_reviews')
    op.drop_index('ix_evidence_submissions_student_goal', table_name='evidence_submissions')
    op.drop_table('evidence_submissions')
    op.drop_index('ix_tutor_messages_thread_time', table_name='tutor_messages')
    op.drop_table('tutor_messages')
    op.drop_index('ix_replan_proposals_student_goal', table_name='replan_proposals')
    op.drop_table('replan_proposals')
    op.drop_index('ix_assessment_attempts_student', table_name='assessment_attempts')
    op.drop_table('assessment_attempts')
    op.drop_index('ix_tutor_threads_student_goal', table_name='tutor_threads')
    op.drop_table('tutor_threads')
    op.drop_index('ix_risks_student_goal_status', table_name='risks')
    op.drop_table('risks')
    op.drop_table('resource_recommendations')
    op.drop_index('ix_progress_snapshots_goal_time', table_name='progress_snapshots')
    op.drop_table('progress_snapshots')
    op.drop_index('ix_progress_events_student_goal_time', table_name='progress_events')
    op.drop_table('progress_events')
    op.drop_index(op.f('ix_phase4_execution_contexts_student_id'), table_name='phase4_execution_contexts')
    op.drop_table('phase4_execution_contexts')
    op.drop_index('ix_phase4_agent_runs_student_goal', table_name='phase4_agent_runs')
    op.drop_table('phase4_agent_runs')
    op.drop_index('ix_mastery_estimates_goal_competency', table_name='mastery_estimates')
    op.drop_table('mastery_estimates')
    op.drop_index('ix_focus_sessions_student_goal', table_name='focus_sessions')
    op.drop_table('focus_sessions')
    op.drop_index('ix_coaching_records_student_goal', table_name='coaching_records')
    op.drop_table('coaching_records')
    op.drop_index('ix_assessment_definitions_goal_status', table_name='assessment_definitions')
    op.drop_table('assessment_definitions')
    op.drop_table('phase4_storage_receipts')
    op.drop_index('ix_notifications_student_unread', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_learning_resources_competency_status', table_name='learning_resources')
    op.drop_table('learning_resources')
    # ### end Alembic commands ###
